# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-12 21:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subsystem',
            name='project',
        ),
        migrations.AddField(
            model_name='subsystem',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='updates.Project'),
            preserve_default=False,
        ),
    ]
