# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-12 22:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0002_auto_20161112_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='ongoing',
            field=models.BooleanField(default=True),
        ),
    ]
