# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-13 01:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0003_project_ongoing'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='quick_description',
            field=models.CharField(default='Description', max_length=140),
            preserve_default=False,
        ),
    ]
