# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-13 02:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0006_subsystem_full_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsystem',
            name='quick_update',
            field=models.CharField(default='quick subsytem update', max_length=140),
            preserve_default=False,
        ),
    ]
