# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-13 02:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0009_subsystem_meeting_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsystem',
            name='meeting_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
