# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-13 02:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0010_subsystem_meeting_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsystem',
            name='meeting_location',
            field=models.CharField(default='Toomey 140', max_length=50),
        ),
    ]
