# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-13 03:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0013_timeline'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeline',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
