# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-13 03:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0015_auto_20161112_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeline',
            name='month',
        ),
        migrations.RemoveField(
            model_name='timeline',
            name='year',
        ),
        migrations.AlterField(
            model_name='timeline',
            name='text',
            field=models.TextField(),
        ),
    ]
