# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-15 22:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0017_generalsubsystem'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsystem',
            name='general_subsystem',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='updates.GeneralSubsystem'),
            preserve_default=False,
        ),
    ]
