# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-15 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0018_subsystem_general_subsystem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subsystem',
            name='full_description',
        ),
        migrations.AddField(
            model_name='subsystem',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
