# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-15 22:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0019_auto_20161115_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subsystem',
            name='name',
        ),
    ]
