# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-16 00:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0021_generalsubsystem_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsubsystem',
            name='image',
            field=models.ImageField(null=True, upload_to=b''),
        ),
    ]
